contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #isoseq channel"
    url: https://nfcore.slack.com/channels/isoseq
    about: Discussion about the nf-core/isoseq pipeline
